services:
  flutter:
    image: ghcr.io/cirruslabs/flutter:stable
    container_name: ordem-paranormal-flutter
    working_dir: /app
    volumes:
      - .:/app
      - pub-cache:/root/.pub-cache
    ports:
      - "8093:8093"
    command: tail -f /dev/null

volumes:
  pub-cache:
